from __future__ import annotations

from app.schemas.filing_fields import FilingFieldDefinition


class FieldRegistryService:
    def __init__(self) -> None:
        self._fields: dict[str, FilingFieldDefinition] = {
            "case_type": FilingFieldDefinition(
                key="case_type",
                label="Case Type",
                field_type="dropdown",
                required=True,
                section="case_type_bench",
                auto_fill_threshold=0.95,
                suggestion_threshold=0.70,
                allowed_values=["CONC", "CRR", "CRA", "MCRC", "WP"],
                aliases={
                    "conc": "CONC",
                    "contempt petition": "CONC",
                    "civil contempt": "CONC",
                    "criminal revision": "CRR",
                    "criminal revision petition": "CRR",
                    "crr": "CRR",
                    "criminal appeal": "CRA",
                    "cra": "CRA",
                    "misc criminal case": "MCRC",
                    "mcrc": "MCRC",
                    "writ petition": "WP",
                    "wp": "WP",
                },
                source_priority=["index_section", "regex", "vector_retrieval", "llm"],
            ),
            "list_type": FilingFieldDefinition(
                key="list_type",
                label="List Type",
                field_type="dropdown",
                required=False,
                section="case_type_bench",
                auto_fill_threshold=0.90,
                suggestion_threshold=0.65,
                allowed_values=["INDIVIDUAL", "REGULAR", "URGENT"],
                aliases={
                    "individual": "INDIVIDUAL",
                    "regular": "REGULAR",
                    "urgent": "URGENT",
                },
                source_priority=["regex", "vector_retrieval", "llm"],
            ),
            "petitioner_name": FilingFieldDefinition(
                key="petitioner_name",
                label="Petitioner Name",
                field_type="text",
                required=True,
                section="petitioner",
                auto_fill_threshold=0.92,
                suggestion_threshold=0.65,
                source_priority=["regex", "vector_retrieval", "llm"],
            ),
            "respondent_name": FilingFieldDefinition(
                key="respondent_name",
                label="Respondent Name",
                field_type="text",
                required=True,
                section="respondent",
                auto_fill_threshold=0.92,
                suggestion_threshold=0.65,
                source_priority=["regex", "vector_retrieval", "llm"],
            ),
            "petitioner_party_type": FilingFieldDefinition(
                key="petitioner_party_type",
                label="Petitioner Individual / Department Type",
                field_type="radio",
                required=False,
                section="petitioner",
                auto_fill_threshold=0.90,
                suggestion_threshold=0.70,
                allowed_values=["Individual", "State Department", "Central Department", "Other Organization"],
                source_priority=["rule", "vector_retrieval", "llm"],
            ),
            "respondent_party_type": FilingFieldDefinition(
                key="respondent_party_type",
                label="Respondent Individual / Department Type",
                field_type="radio",
                required=False,
                section="respondent",
                auto_fill_threshold=0.90,
                suggestion_threshold=0.70,
                allowed_values=["Individual", "State Department", "Central Department", "Other Organization"],
                source_priority=["rule", "vector_retrieval", "llm"],
            ),
            "advocate_name": FilingFieldDefinition(
                key="advocate_name",
                label="Advocate Name",
                field_type="text",
                required=False,
                section="advocate",
                auto_fill_threshold=0.88,
                suggestion_threshold=0.65,
                multi_value=True,
                source_priority=["regex", "vector_retrieval", "llm"],
            ),
            "advocate_enrol_no": FilingFieldDefinition(
                key="advocate_enrol_no",
                label="Advocate Enrol No",
                field_type="text",
                required=False,
                section="advocate",
                auto_fill_threshold=0.90,
                suggestion_threshold=0.70,
                multi_value=True,
                source_priority=["regex", "vector_retrieval"],
            ),
            "advocate_enrol_year": FilingFieldDefinition(
                key="advocate_enrol_year",
                label="Advocate Enrol Year",
                field_type="text",
                required=False,
                section="advocate",
                auto_fill_threshold=0.90,
                suggestion_threshold=0.70,
                multi_value=True,
                source_priority=["regex", "vector_retrieval"],
            ),
            "advocate_mobile": FilingFieldDefinition(
                key="advocate_mobile",
                label="Advocate Mobile",
                field_type="mobile",
                required=False,
                section="advocate",
                auto_fill_threshold=0.88,
                suggestion_threshold=0.70,
                multi_value=True,
                source_priority=["regex", "vector_retrieval"],
            ),
            "advocate_remark": FilingFieldDefinition(
                key="advocate_remark",
                label="Advocate Remark",
                field_type="text",
                required=False,
                section="advocate",
                auto_fill_threshold=0.95,
                suggestion_threshold=0.75,
                multi_value=True,
                source_priority=["system"],
            ),
            "with_application": FilingFieldDefinition(
                key="with_application",
                label="With Application",
                field_type="checkbox",
                required=False,
                section="case_type_bench",
                auto_fill_threshold=0.88,
                suggestion_threshold=0.70,
                allowed_values=["true"],
                source_priority=["regex", "vector_retrieval"],
            ),
            "hide_party_petitioner": FilingFieldDefinition(
                key="hide_party_petitioner",
                label="Hide Party Name (Petitioner)",
                field_type="checkbox",
                required=False,
                section="petitioner",
                auto_fill_threshold=0.95,
                suggestion_threshold=0.80,
                allowed_values=["true"],
                source_priority=["regex", "vector_retrieval"],
            ),
            "hide_party_respondent": FilingFieldDefinition(
                key="hide_party_respondent",
                label="Hide Party Name (Respondent)",
                field_type="checkbox",
                required=False,
                section="respondent",
                auto_fill_threshold=0.95,
                suggestion_threshold=0.80,
                allowed_values=["true"],
                source_priority=["regex", "vector_retrieval"],
            ),
            "differently_abled_petitioner": FilingFieldDefinition(
                key="differently_abled_petitioner",
                label="Differently Abled (Petitioner)",
                field_type="checkbox",
                required=False,
                section="petitioner",
                auto_fill_threshold=0.88,
                suggestion_threshold=0.70,
                allowed_values=["true"],
                source_priority=["regex", "vector_retrieval"],
            ),
            "differently_abled_respondent": FilingFieldDefinition(
                key="differently_abled_respondent",
                label="Differently Abled (Respondent)",
                field_type="checkbox",
                required=False,
                section="respondent",
                auto_fill_threshold=0.88,
                suggestion_threshold=0.70,
                allowed_values=["true"],
                source_priority=["regex", "vector_retrieval"],
            ),
            "advocate_rows": FilingFieldDefinition(
                key="advocate_rows",
                label="Advocate Rows",
                field_type="text",
                required=False,
                section="advocate",
                auto_fill_threshold=0.88,
                suggestion_threshold=0.70,
                multi_value=True,
                source_priority=["regex", "vector_retrieval"],
            ),
            "petitioner_more_details": FilingFieldDefinition(
                key="petitioner_more_details",
                label="Petitioner More Details",
                field_type="text",
                required=False,
                section="petitioner",
                auto_fill_threshold=0.85,
                suggestion_threshold=0.65,
                source_priority=["regex", "vector_retrieval"],
            ),
            "respondent_more_details": FilingFieldDefinition(
                key="respondent_more_details",
                label="Respondent More Details",
                field_type="text",
                required=False,
                section="respondent",
                auto_fill_threshold=0.85,
                suggestion_threshold=0.65,
                source_priority=["regex", "vector_retrieval"],
            ),
        }

    def get_all(self) -> list[FilingFieldDefinition]:
        return list(self._fields.values())

    def get(self, key: str) -> FilingFieldDefinition:
        return self._fields[key]

    def as_dict(self) -> dict[str, FilingFieldDefinition]:
        return self._fields
